### ISSUE TITLE
The game registers an extra row at the bottom and column at the right

### ISSUE THREAD

**Issue by numberQ** [seniordesign2/game-client#4]
This bug was introduced when switched to a nested vector model of coordinates. Even though the screen seems to be initialized with 0 to n-1 rows and columns, the player can move onto the nth row or column without problem.

**Comment by numberQ** [comment]
Discovered that this is because `assoc-in` appends a value to a collection if it tries to access one more than the maximum index. Once we introduce boundary detection to player movement, this should fix itself, so I'll leave this issue open until then.

**Comment by flamwenco** [comment]
We now have collision detection implemented, which also ensures the player can't walk out of bounds, so this should no longer be an issue.
